name: Build ZMK firmware
on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
  
  collect-bridge-proto:
    uses: Samsuper12/bridge-zmk-module/.github/workflows/collect-proto-files.yml@main